### ISSUE TITLE
[BACKEND] La modifica dell'ente non funziona

### ISSUE THREAD

**Issue by Maxelweb** [RedRoundRobin/swe-api#136]
**Descrizione del bug**
Un admin non può modificare un ente dalla webapp.

**Modifica da fare**
Un admin deve poter modificare un ente qualunque nelle sue due informazioni (nome e luogo).

**Comment by FouadM96** [comment]
Ora ci do un'occhiata

**Comment by FouadM96** [comment]
Dovrei aver sistemato
