### ISSUE TITLE
[BUG] Data e ora invio ultima configurazione

### ISSUE THREAD

**Issue by Maxelweb** [RedRoundRobin/swe-api#137]
**Descrizione del bug**
Data ora invio ultima configurazione non viene aggiornato nel DB.

**Modifica da fare**
Ogni volta che si riceve un poke di invio nuova configurazione a un determinato gateway, va fatta una query per aggiornare a `NOW()` l'ultimo invio.

**Comment by nfrison** [comment]
Implementato in 815f365a0c38ebe34e87548c51caf03b241f2a0d
