### ISSUE TITLE
Creazione API per Telegram

### ISSUE THREAD

**Issue by aletomm** [RedRoundRobin/swe-api#15]
Creazione funzione per il check dell'username di Telegram ed eventuale salvataggio della chat id. Lo scheletro della funzione è già presente nella repo nel branch feature/aggiuntaPostgreSpring.
**_La funzione deve ritornare un int non una String_**

CODICI:
0 se l'username di telegram non è presente nel Database
1 se l'username di Telegram è presente e il chatId è vuoto (Bisogna quindi inserirlo)
2 se L'username di Telegram è presente e c'è già la chatId

**Comment by aletomm** [comment]
funzione per la richiesta /status/usernameTelegram
Controlla lo status dell'utente e ritorna i suo dati in un qualche formato

**Comment by nfrison** [comment]
API:
----
- ####Autenticazione telegram
    /* Richiede: Telegram Name e chat id<br>
    */ Ritorna: il relativo token<br>
    - Autenticazione semplice
        - __Metodo__: POST
        - __Header__: .JSON
        - __URI__: /auth/telegram
        - __Body__: {<br>
                &emsp;&emsp;TelegramName: "telegram name",<br>
                &emsp;&emsp;TelegramChat: "chat id"<br>
            &emsp;}
        - __Risposta__: .JSON :: {<br>
                &emsp;&emsp;token: "",<br>
            &emsp;}
